"""
Genereer een wit-variant van het Act Right-logo voor gebruik op moss-
achtergronden (PDF cover, CTA-pagina, banners).

Input  : src/assets/actright-logo.png  (lime atom + moss wordmark)
Output : src/assets/generated/actright-logo-white.png
         src/assets/generated/actright-logo-white-base64.ts

Werking: alle moss-getinte pixels (donkere olijf) worden omgezet naar
Pure Light. Lime-pixels (atom) blijven onveranderd. Transparant blijft
transparant.
"""
import base64
from pathlib import Path
from PIL import Image

REPO = Path(__file__).parent.parent
SRC = REPO / "src" / "assets" / "actright-logo.png"
OUT_PNG = REPO / "src" / "assets" / "generated" / "actright-logo-white.png"
OUT_TS = REPO / "src" / "assets" / "generated" / "actright-logo-white-base64.ts"

# Act Right kleuren (canonical)
MOSS_R, MOSS_G, MOSS_B = 44, 48, 28      # #2C301C
LIME_R, LIME_G, LIME_B = 228, 230, 95    # #E4E65F
PURE_LIGHT = (255, 254, 246)             # #FFFEF6

img = Image.open(SRC).convert("RGBA")
w, h = img.size
print(f"Source: {w}x{h}")

px = img.load()
swapped = 0
for y in range(h):
    for x in range(w):
        r, g, b, a = px[x, y]
        if a == 0:
            continue
        # Moss-detection: donker, weinig verzadigd-rood, wat groen overhellend
        if r < 80 and g < 90 and b < 70:
            px[x, y] = (*PURE_LIGHT, a)
            swapped += 1
        # Lime: onveranderd (pixels met R+G > ~300 en relatief weinig blauw)

print(f"Swapped {swapped} moss-pixels to pure-light")
img.save(OUT_PNG, "PNG", optimize=True)
print(f"Wrote {OUT_PNG.name} ({OUT_PNG.stat().st_size // 1024} KB)")

# Base64 TS-module voor Vite-bundling
b64 = base64.b64encode(OUT_PNG.read_bytes()).decode("ascii")
OUT_TS.write_text(
    f'''// Auto-generated by scripts/generate-white-logo.py
// Variant van actright-logo voor gebruik op moss-achtergronden
// (PDF cover, CTA-pagina, donkere headers).

export const logoWhitePngBase64 =
  "{b64}";
export const logoWhiteDataUrl = `data:image/png;base64,${{logoWhitePngBase64}}`;
''',
    encoding="utf-8",
)
print(f"Wrote {OUT_TS.name} ({len(b64) // 1024} KB base64)")
