"""
Genereer PDF-assets als base64-encoded TypeScript modules.

Haalt Funnel-variable-fonts uit het Google Fonts repository, instantieert
statische gewicht-varianten via fontTools, en encodeert ze (plus het
Act Right-logo) als base64 in TypeScript-modules. Vite bundle't die mee
in de client-bundle, zodat jsPDF ze kan embedden.

Runtime: python scripts/prepare-pdf-assets.py

Output:
  src/assets/generated/funnel-display-bold.ts
  src/assets/generated/funnel-sans-light.ts
  src/assets/generated/funnel-sans-regular.ts
  src/assets/generated/actright-logo-base64.ts
"""
import base64
import io
import urllib.request
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.mutator import instantiateVariableFont

REPO = Path(__file__).parent.parent
OUT = REPO / "src" / "assets" / "generated"
OUT.mkdir(parents=True, exist_ok=True)

DISPLAY_VF_URL = (
    "https://raw.githubusercontent.com/google/fonts/main/"
    "ofl/funneldisplay/FunnelDisplay%5Bwght%5D.ttf"
)
SANS_VF_URL = (
    "https://raw.githubusercontent.com/google/fonts/main/"
    "ofl/funnelsans/FunnelSans%5Bwght%5D.ttf"
)


def fetch(url: str) -> bytes:
    print(f"  Downloading {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "act-right-pdf-prep"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def extract_static(vf_bytes: bytes, weight: int, family_name: str) -> bytes:
    """Extraheer een statische instance op de gekozen wght-as uit een variable font."""
    vf = TTFont(io.BytesIO(vf_bytes))
    # Handhaaf alleen gewicht-as; andere assen blijven op default
    axis_values = {"wght": weight}
    static = instantiateVariableFont(vf, axis_values)
    out = io.BytesIO()
    static.save(out)
    print(f"  Extracted {family_name} weight={weight}: {len(out.getvalue()) // 1024} KB")
    return out.getvalue()


def write_font_module(slug: str, filename: str, b64: str, jspdf_name: str, style: str):
    path = OUT / f"{slug}.ts"
    content = f'''// Auto-generated by scripts/prepare-pdf-assets.py
// Bron: {filename}
// jsPDF-registratienaam: "{jspdf_name}" style "{style}"

export const fontFile = "{filename}";
export const jspdfName = "{jspdf_name}";
export const jspdfStyle = "{style}";
export const base64 =
  "{b64}";
'''
    path.write_text(content, encoding="utf-8")
    print(f"  Wrote {path.name} ({len(b64) // 1024} KB base64)")


# --- Fonts ---
print("Fetching variable fonts...")
display_vf = fetch(DISPLAY_VF_URL)
sans_vf = fetch(SANS_VF_URL)

print("\\nExtracting static instances...")
# Funnel Display Bold (700) — voor headings
display_bold = extract_static(display_vf, 700, "FunnelDisplay")
# Funnel Sans Light (300) — voor body
sans_light = extract_static(sans_vf, 300, "FunnelSans")
# Funnel Sans Regular (400) — voor body-emphasis
sans_regular = extract_static(sans_vf, 400, "FunnelSansRegular")

print("\\nEncoding to base64 + writing modules...")
write_font_module(
    "funnel-display-bold",
    "FunnelDisplay-Bold.ttf",
    base64.b64encode(display_bold).decode("ascii"),
    "FunnelDisplay",
    "bold",
)
write_font_module(
    "funnel-sans-light",
    "FunnelSans-Light.ttf",
    base64.b64encode(sans_light).decode("ascii"),
    "FunnelSans",
    "normal",
)
write_font_module(
    "funnel-sans-regular",
    "FunnelSans-Regular.ttf",
    base64.b64encode(sans_regular).decode("ascii"),
    "FunnelSansRegular",
    "normal",
)

# --- Logo ---
print("\\nProcessing logo...")
logo_path = REPO / "src" / "assets" / "actright-logo.png"
logo_data = logo_path.read_bytes()
logo_b64 = base64.b64encode(logo_data).decode("ascii")
logo_module = OUT / "actright-logo-base64.ts"
logo_module.write_text(
    f'''// Auto-generated by scripts/prepare-pdf-assets.py
// Bron: src/assets/actright-logo.png
// Voor gebruik in jsPDF via doc.addImage(logoDataUrl, "PNG", ...).

export const logoPngBase64 =
  "{logo_b64}";
export const logoDataUrl = `data:image/png;base64,${{logoPngBase64}}`;
''',
    encoding="utf-8",
)
print(f"  Wrote {logo_module.name} ({len(logo_b64) // 1024} KB base64)")

print(f"\\nKlaar. Output in {OUT}")
